Support switching drivers between vfio-pci and nvidia

diff --git a/driver-manager b/driver-manager
--- a/driver-manager
+++ b/driver-manager
@@ -36,8 +36,11 @@ MIG_MANAGER_DEPLOYED=""
 SANDBOX_VALIDATOR_DEPLOYED=""
 SANDBOX_PLUGIN_DEPLOYED=""
 VGPU_DEVICE_MANAGER_DEPLOYED=""
-NODE_TYPE_LABEL=""
+NODE_LABEL_FOR_GPU_POD_EVICTION=$(echo ${NODE_LABEL_FOR_GPU_POD_EVICTION} | sed -e "s/=.*$//g")
+CUSTOM_OPERAND_NODE_LABEL_VALUE=""
 AUTO_UPGRADE_POLICY_ENABLED=""
+GPU_DIRECT_RDMA_ENABLED=${GPU_DIRECT_RDMA_ENABLED:-"false"}
+USE_HOST_MOFED=${USE_HOST_MOFED:-"false"}
 
 _drain_k8s_node() {
     echo "Draining node ${NODE_NAME}..."
@@ -229,14 +232,17 @@ _fetch_current_labels() {
     fi
     echo "Current value of 'nvidia.com/gpu.deploy.vgpu-device-manager=${VGPU_DEVICE_MANAGER_DEPLOYED}'"
 
-    echo "Getting current value of the 'nodeType' node label(used by NVIDIA Fleet Command)"
-    NODE_TYPE_LABEL=$(kubectl get nodes ${NODE_NAME} -o=jsonpath='{$.metadata.labels.nodeType}')
-    if [ "${?}" != "0" ]; then
-        echo "Unable to get the value of the 'nodeType' label"
-        exit 1
+    if [ "${NODE_LABEL_FOR_GPU_POD_EVICTION}" != "" ]; then
+        echo "Getting current value of the '${NODE_LABEL_FOR_GPU_POD_EVICTION}' node label used by custom operands"
+        LABEL_KEY=$(echo $NODE_LABEL_FOR_GPU_POD_EVICTION | sed -e "s/\./\\\./g")
+        JSON_LABEL_PATH="{$.metadata.labels.$LABEL_KEY}"
+        CUSTOM_OPERAND_NODE_LABEL_VALUE=$(kubectl get nodes ${NODE_NAME} -o=jsonpath=${JSON_LABEL_PATH})
+        if [ "${?}" != "0" ]; then
+            echo "Unable to get the value of the '${NODE_LABEL_FOR_GPU_POD_EVICTION}' label"
+            exit 1
+        fi
+        echo "Current value of '${NODE_LABEL_FOR_GPU_POD_EVICTION}=${CUSTOM_OPERAND_NODE_LABEL_VALUE}'"
     fi
-    echo "Current value of 'nodeType=${NODE_TYPE_LABEL}'"
-
 }
 
 _evict_required_gpu_operator_components() {
@@ -308,11 +314,11 @@ _evict_all_gpu_operator_components() {
         return 1
     fi
 
-    # check for nodeType=gpu label used by NVIDIA Fleet Command
-    if [ "${NODE_TYPE_LABEL}" == "gpu" ]; then
-        echo "Shutting down GPU clients on NVIDIA Fleet Command"
+    # check if a custom operand node selector label is provided for eviction
+    if [ "${CUSTOM_OPERAND_NODE_LABEL_VALUE}" != "" ]; then
+        echo "Shutting down GPU clients using node selector label ${NODE_LABEL_FOR_GPU_POD_EVICTION}=${CUSTOM_OPERAND_NODE_LABEL_VALUE}"
         kubectl label --overwrite node ${NODE_NAME} \
-            nodeType=$(_maybe_set_paused ${NODE_TYPE_LABEL})
+            ${NODE_LABEL_FOR_GPU_POD_EVICTION}=$(_maybe_set_paused ${CUSTOM_OPERAND_NODE_LABEL_VALUE})
 
         if [ "$?" != "0" ]; then
             return 1
@@ -447,11 +453,11 @@ _reschedule_gpu_operator_components() {
         return 1
     fi
 
-    # check for nodeType=gpu label used by NVIDIA Fleet Command
-    if [ "${NODE_TYPE_LABEL}" != "" ]; then
-        echo "Restarting GPU clients on NVIDIA Fleet Command"
+    # check for custom operand node selector label
+    if [ "${CUSTOM_OPERAND_NODE_LABEL_VALUE}" != "" ]; then
+        echo "Restarting GPU clients using node selector label ${NODE_LABEL_FOR_GPU_POD_EVICTION}=${CUSTOM_OPERAND_NODE_LABEL_VALUE}"
         kubectl label --overwrite node ${NODE_NAME} \
-            nodeType=$(_maybe_set_true ${NODE_TYPE_LABEL})
+            ${NODE_LABEL_FOR_GPU_POD_EVICTION}=$(_maybe_set_true ${CUSTOM_OPERAND_NODE_LABEL_VALUE})
         if [ "$?" != "0" ]; then
             return 1
         fi
@@ -524,18 +530,47 @@ _host_driver() {
     return 1
 }
 
-uninstall_driver() {
-    # don't attempt to un-install if driver is pre-installed on the node
-    if _host_driver; then
-        echo "NVIDIA GPU driver is already pre-installed on the node, disabling the containerized driver on the node"
-        kubectl label --overwrite \
-          node ${NODE_NAME} \
-          nvidia.com/gpu.deploy.driver=pre-installed
-        # add wait here as pod termination can take 30s due to default grace-period
-        sleep 60
-        exit 1
+# Check if mellanox devices are present
+_mellanox_devices_present() {
+    devices_found=0
+    for dev in /sys/bus/pci/devices/*; do
+        read vendor < $dev/vendor
+        if [ "$vendor" = "0x15b3" ]; then
+            echo "Mellanox device found at $(basename $dev)"
+            return 0
+        fi
+    done
+    echo "No Mellanox devices were found..."
+    return 1
+}
+
+_gpu_direct_rdma_enabled() {
+    if [ "${GPU_DIRECT_RDMA_ENABLED}" = "true" ]; then
+        # check if mellanox cards are present
+        if  _mellanox_devices_present; then
+            return 0
+        fi
+    fi
+    return 1
+}
+
+_wait_for_mofed_driver() {
+    # check for mlx5_core module to be loaded
+    cmd="lsmod | grep mlx5_core"
+
+    if [ "${USE_HOST_MOFED}" != "true" ]; then
+        # when MOFED container is running use readiness flag set by the driver container instaed
+        cmd="stat /run/mellanox/drivers/.driver-ready"
     fi
 
+    until bash -c "${cmd}"
+    do
+        echo "Waiting for MOFED to be installed..."
+        sleep 5
+    done
+}
+
+switch_driver() {
     # fetch current status of all component labels
     _fetch_current_labels
 
@@ -554,43 +589,25 @@ uninstall_driver() {
             # are running on the node and cannot be deleted. Attempt
             # to drain the node in this case.
             echo "Failed to drain node of GPU pods"
-            if ! _is_auto_drain_enabled; then
-                echo "Cannot proceed until all GPU pods are drained from the node. Exiting."
-                _exit_failed
-            fi
-            echo "Attempting node drain"
-            trap '_exit_failed' ERR
-            _drain_k8s_node
-            _cleanup_driver
         fi
     fi
 
-
-    # check if driver is already loaded
-    if _driver_loaded; then
-        _cleanup_driver
-        if [ "$?" != "0" ]; then
-            if _is_auto_drain_enabled; then
-                echo "Unable to cleanup driver modules, attempting again with node drain..."
-                trap '_exit_failed' ERR
-                _drain_k8s_node
-                _cleanup_driver
-            else
-                echo "Failed to uninstall nvidia driver components"
-                _exit_failed
-            fi
-        fi
-        echo "Successfully uninstalled nvidia driver components"
-    fi
 
     # If vfio-pci driver is in use, ensure we unbind it from all devices.
-    # If vfio-pci driver is not in use and we have reached this point, all
-    # devices will not be bound to any driver, so the below unbind operation
-    # will be a no-op.
-    vfio-manage unbind --all
+    if [ "$ALL_TO_NVIDIA" != "true" ]; then
+        vfio-manage unbind --all
+    else
+        vfio-manage unbind --all-to-nvidia true
+    fi
     if [ "$?" != "0" ]; then
         echo "Unable to unbind vfio-pci driver from all devices"
         _exit_failed
+    fi
+
+    # when GPUDirectRDMA is enabled, wait until MOFED driver has finished installing
+    if _gpu_direct_rdma_enabled; then
+        echo "GPUDirectRDMA is enabled, validating MOFED driver installation"
+        _wait_for_mofed_driver
     fi
 
     if _is_gpu_pod_eviction_enabled || _is_auto_drain_enabled; then
@@ -608,7 +625,10 @@ uninstall_driver() {
         fi
         echo "Successfully unloaded nouveau driver"
     fi
-    exit 0
+
+    if [ "$ALL_TO_NVIDIA" != "true" ]; then
+        vfio-manage bind --all
+    fi
 }
 
 preflight_check() {
@@ -628,6 +648,7 @@ _unload_driver() {
     local nvidia_peermem_refs=0
     local nvidia_vgpu_vfio_refs=0
     local nvidia_fs_refs=0
+    local gdrdrv_refs=0
 
     echo "Unloading NVIDIA driver kernel modules..."
     if [ -f /sys/module/nvidia_modeset/refcnt ]; then
@@ -655,6 +676,11 @@ _unload_driver() {
         rmmod_args+=("nvidia_vgpu_vfio")
         ((++nvidia_deps))
     fi
+    if [ -f /sys/module/gdrdrv/refcnt ]; then
+            gdrdrv_refs=$(< /sys/module/gdrdrv/refcnt)
+            rmmod_args+=("gdrdrv")
+            ((++nvidia_deps))
+    fi
     if [ -f /sys/module/nvidia/refcnt ]; then
         nvidia_refs=$(< /sys/module/nvidia/refcnt)
         rmmod_args+=("nvidia")
@@ -668,7 +694,7 @@ _unload_driver() {
         #     nvidia              35315712  2
         #     mdev                   24576  2 vfio_mdev,nvidia_vgpu_vfio
         :
-    elif [ ${nvidia_refs} -gt ${nvidia_deps} ] || [ ${nvidia_uvm_refs} -gt 0 ] || [ ${nvidia_modeset_refs} -gt 0 ] || [ ${nvidia_peermem_refs} -gt 0 ] || [ ${nvidia_vgpu_vfio_refs} -gt 0 ] || [ ${nvidia_fs_refs} -gt 0 ]; then
+    elif [ ${nvidia_refs} -gt ${nvidia_deps} ] || [ ${nvidia_uvm_refs} -gt 0 ] || [ ${nvidia_modeset_refs} -gt 0 ] || [ ${nvidia_peermem_refs} -gt 0 ] || [ ${nvidia_vgpu_vfio_refs} -gt 0 ] || [ ${nvidia_fs_refs} -gt 0 ] || [ ${gdrdrv_refs} -gt 0 ]; then
         # run lsmod to debug module usage
         lsmod | grep nvidia
         echo "Could not unload NVIDIA driver kernel modules, driver is in use" >&2
@@ -687,8 +713,8 @@ _unload_driver() {
 # Unmount the driver rootfs from the run directory.
 _unmount_rootfs() {
     echo "Unmounting NVIDIA driver rootfs..."
-    if findmnt -r -o TARGET | grep "/run/nvidia/driver" > /dev/null; then
-        umount -l -R /run/nvidia/driver
+    if findmnt -r -o TARGET | grep "${DRIVER_ROOT}" > /dev/null; then
+        umount -l -R ${DRIVER_ROOT}
         return 0
     fi
     return 1
@@ -714,7 +740,7 @@ usage() {
 Usage: $0 COMMAND [ARG...]
 
 Commands:
-  uninstall_driver
+  switch_driver [-n | --all-to-nvidia]
   preflight_check
 EOF
     exit 1
@@ -725,7 +751,7 @@ if [ $# -eq 0 ]; then
 fi
 command=$1; shift
 case "${command}" in
-    uninstall_driver) ;;
+    switch_driver) options=$(getopt -o n: --long all-to-nvidia: -- "$@");;
     preflight_check) ;;
     *) usage ;;
 esac
@@ -733,4 +759,17 @@ if [ $? -ne 0 ]; then
     usage
 fi
 
+eval set -- "${options}"
+
+ALL_TO_NVIDIA=false
+for opt in ${options}; do
+    case "$opt" in
+    -n | --all-to-nvidia) ALL_TO_NVIDIA=true; shift 2;;
+    -h | --help) shift;;
+    --) shift; break ;;
+    esac
+done
+if [ $# -ne 0 ]; then
+    usage
+fi
 $command
